version: '3.1'

services:
  client:
    build: .
    volumes:
      - "./client:/app"
    ports:
      - "3031:3000"
    depends_on:
      - api

  server:
    build: .
    volumes:
      - "./server:/app"
    ports:
      - "3003:3000"
